### ISSUE TITLE
恢复数据库提示文件不存在

### ISSUE THREAD

**Issue by shuncon** [long2ice/databack#3]
2023-04-24 08:12:44.690 | INFO     | rearq.worker:_run_job:172 -   0.01s → 51d3c700795d49b78ed09d7baaa4be9c:run_restore(2)
2023-04-24 08:12:44.693 | ERROR    | databack.tasks:run_restore:107 - [Errno 2] No such file or directory: '/tmp/tmp5_0kg7ed/2023-04-24_07-59-38.sql.tar.gz'
Traceback (most recent call last):

  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
    │   │    └ <Command main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fb6a02af1a0>
           └ <Command main>
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fb6a0ea4b10>
         │    └ <function Command.invoke at 0x7fb6a02afd80>
         └ <Command main>
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'host': '0.0.0.0', 'port': 8000, 'app': 'databack.app:app', 'uds': None, 'fd': None, 'reload': False, 'reload_dirs': (), 're...
           │   │      │    │           └ <click.core.Context object at 0x7fb6a0ea4b10>
           │   │      │    └ <function main at 0x7fb6a00ae020>
           │   │      └ <Command main>
           │   └ <function Context.invoke at 0x7fb6a02ae700>
           └ <click.core.Context object at 0x7fb6a0ea4b10>
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'host': '0.0.0.0', 'port': 8000, 'app': 'databack.app:app', 'uds': None, 'fd': None, 'reload': False, 'reload_dirs': (), 're...
                       └ ()
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/main.py", line 403, in main
    run(
    └ <function run at 0x7fb6a0308cc0>
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/main.py", line 568, in run
    server.run()
    │      └ <function Server.run at 0x7fb6a030b420>
    └ <uvicorn.server.Server object at 0x7fb6a02e76d0>
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fb6a030b4c0>
           │       │   └ <uvicorn.server.Server object at 0x7fb6a02e76d0>
           │       └ <function run at 0x7fb6a069b560>
           └ <module 'asyncio' from '/usr/lib/python3.11/asyncio/__init__.py'>
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Server.serve at 0x7fb6a00ba680>
           │      └ <function Runner.run at 0x7fb6a052ae80>
           └ <asyncio.runners.Runner object at 0x7fb6a00bf150>
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Server.serve() running at /usr/local/lib/python3.11/dist-packages/uvicorn/server.py:79> wai...
           │    │     └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           │    └ <uvloop.Loop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x7fb6a00bf150>

> File "/databack/databack/tasks.py", line 103, in run_restore
    await data_source_obj.restore(local_file)
          │               │       └ '/tmp/tmp5_0kg7ed/2023-04-24_07-59-38.sql.tar.gz'
          │               └ <function MySQL.restore at 0x7fb69c8d5760>
          └ <databack.datasource.mysql.MySQL object at 0x7fb69c8533d0>

  File "/databack/databack/datasource/mysql.py", line 53, in restore
    file = await self.get_restore(file)
                 │    │           └ '/tmp/tmp5_0kg7ed/2023-04-24_07-59-38.sql.tar.gz'
                 │    └ <function Base.get_restore at 0x7fb69ca577e0>
                 └ <databack.datasource.mysql.MySQL object at 0x7fb69c8533d0>

  File "/databack/databack/datasource/__init__.py", line 38, in get_restore
    await aioshutil.unpack_archive(file, temp_dir)
          │         │              │     └ '/tmp/tmpyi67rgs3'
          │         │              └ '/tmp/tmp5_0kg7ed/2023-04-24_07-59-38.sql.tar.gz'
          │         └ <function unpack_archive at 0x7fb69ca55300>
          └ <module 'aioshutil' from '/usr/local/lib/python3.11/dist-packages/aioshutil/__init__.py'>

  File "/usr/local/lib/python3.11/dist-packages/aioshutil/__init__.py", line 205, in run_in_executor
    return await loop.run_in_executor(None, pfunc)
                 │    │                     └ functools.partial(<function unpack_archive at 0x7fb6a01b0d60>, '/tmp/tmp5_0kg7ed/2023-04-24_07-59-38.sql.tar.gz', '/tmp/tmpyi...
                 │    └ <method 'run_in_executor' of 'uvloop.loop.Loop' objects>
                 └ <uvloop.Loop running=True closed=False debug=False>
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             │        │            └ None
             │        └ None
             └ None
  File "/usr/lib/python3.11/shutil.py", line 1316, in unpack_archive
    func(filename, extract_dir, **kwargs)
    │    │         │              └ {}
    │    │         └ '/tmp/tmpyi67rgs3'
    │    └ '/tmp/tmp5_0kg7ed/2023-04-24_07-59-38.sql.tar.gz'
    └ <function _unpack_tarfile at 0x7fb6a01b0c20>
  File "/usr/lib/python3.11/shutil.py", line 1239, in _unpack_tarfile
    tarobj = tarfile.open(filename)
             │       │    └ '/tmp/tmp5_0kg7ed/2023-04-24_07-59-38.sql.tar.gz'
             │       └ <bound method TarFile.open of <class 'tarfile.TarFile'>>
             └ <module 'tarfile' from '/usr/lib/python3.11/tarfile.py'>
  File "/usr/lib/python3.11/tarfile.py", line 1632, in open
    return func(name, "r", fileobj, **kwargs)
           │    │          │          └ {}
           │    │          └ None
           │    └ '/tmp/tmp5_0kg7ed/2023-04-24_07-59-38.sql.tar.gz'
           └ <bound method TarFile.gzopen of <class 'tarfile.TarFile'>>
  File "/usr/lib/python3.11/tarfile.py", line 1698, in gzopen
    fileobj = GzipFile(name, mode + "b", compresslevel, fileobj)
              │        │     │           │              └ None
              │        │     │           └ 9
              │        │     └ 'r'
              │        └ '/tmp/tmp5_0kg7ed/2023-04-24_07-59-38.sql.tar.gz'
              └ <class 'gzip.GzipFile'>
  File "/usr/lib/python3.11/gzip.py", line 174, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
              │    │           │        │    │         └ 'rb'
              │    │           │        │    └ '/tmp/tmp5_0kg7ed/2023-04-24_07-59-38.sql.tar.gz'
              │    │           │        └ <built-in function open>
              │    │           └ <module 'builtins' (built-in)>
              │    └ None
              └ <unprintable GzipFile object>

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp5_0kg7ed/2023-04-24_07-59-38.sql.tar.gz'
2023-04-24 08:12:44.703 | INFO     | rearq.worker:_run_job:210 -   0.01s ← 51d3c700795d49b78ed09d7baaa4be9c:run_restore(2) ● None
2023-04-24 08:12:50.834 | INFO     | uvicorn.protocols.http.httptools_impl:send:506 - 192.168.145.1:60610 - "GET /api/restore?limit=10&offset=0 HTTP/1.1" 200

数据库备份路径：/data/shun-mysqlbak/shunbakdata
怎么就变成：/tmp/tmp5_0kg7ed/2023-04-24_07-59-38.sql.tar.gz
而且恢复的过程，不是调用客户端连接上mysql再导入嘛

**Comment by shuncon** [comment]
使用本地恢复依旧提示：[Errno 2] No such file or directory: '/tmp/tmpkflfkpnw/2023-04-24_07-59-38.sql.tar.gz'
{"path":"/databack/shunbakdata/2023-04-24_07-59-38.sql.tar.gz"}
![image](https://user-images.githubusercontent.com/25509201/233941174-e6e1fc36-ca71-421c-aff0-358cb3c179f2.png)

**Comment by long2ice** [comment]
先确定这个文件在吗？恢复的逻辑是先从存储下载到本地临时路径，然后解压恢复

**Comment by shuncon** [comment]
/data/shun-mysqlbak/shunbakdata# ls
2023-04-24_07-59-38.sql.tar.gz
root@shun:/data/shun-mysqlbak/shunbakdata# docker exec -it mysqldataback-databack-1 bash
root@shun:/databack# ls
conftest.py  docker      images   Makefile    poetry.lock     README.md    static
databack     get-pip.py  LICENSE  migrations  pyproject.toml  shunbakdata  tests
root@shun:/databack# cd databack/
api/           depends.py     i18n/          __pycache__/   static.py      validators.py
app.py         discover.py    __init__.py    scheduler.py   storage/       
constants.py   enums.py       log.py         schema/        tasks.py       
datasource/    exceptions.py  models.py      settings.py    utils.py       
root@shun:/databack# cd shunbakdata/
root@shun:/databack/shunbakdata# pwd
/databack/shunbakdata
root@shun:/databack/shunbakdata# ^Chunbakdata/
root@shun:/databack/shunbakdata# ls
2023-04-24_07-59-38.sql.tar.gz

文件是真实存在的，由于是docker部署的， 那么还原的路径应该写容器内的绝对路径才对

**Comment by long2ice** [comment]
恢复时候的本地路径是指恢复到本地某一个路径，不是这个备份文件的路径

**Comment by shuncon** [comment]
> 恢复时候的本地路径是指恢复到本地某一个路径，不是这个备份文件的路径

就是将压缩文件放到需要恢复的mysql主机上是嘛

**Comment by shuncon** [comment]
![image](https://user-images.githubusercontent.com/25509201/236359057-783ad5e4-24f7-4430-95df-a78b759ebfe5.png)
好像定时任务有点问题 哪怕我设置 0 4 * * * /0 0 * * * 都不能凌晨执行备份，只能一直是中午12点备份

**Comment by long2ice** [comment]
https://github.com/long2ice/databack#timezone，看这里

**Comment by shuncon** [comment]
默认情况下，将使用时区进行表达式。如果要使用其他时区，可以设置 环境变量到您的时区。databack UT Ccron TZ  这咋理解 emmm

**Comment by long2ice** [comment]
如果你是 docker 部署的，直接加个环境变量：TZ=Asia/Shanghai

**Comment by shuncon** [comment]
谢谢大佬啊！！！

**Comment by shuncon** [comment]
vim .env
TZ=Asia/Shanghai
